// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This file needs to be regenerated using the FlutterFire CLI:
///
/// ```bash
/// # Install FlutterFire CLI (if not already installed)
/// dart pub global activate flutterfire_cli
///
/// # Configure Firebase for your project
/// flutterfire configure
/// ```
///
/// This will automatically generate the correct configuration based on your
/// Firebase project.
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase config
  // Run `flutterfire configure` to generate the correct values

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsYOGLwHIQmFqplBD49WZ6nVXw7E4QdjI',
    appId: '1:992265233794:web:a345c9377583f8553a5b9b',
    messagingSenderId: '992265233794',
    projectId: 'mobileitt632',
    authDomain: 'mobileitt632.firebaseapp.com',
    storageBucket: 'mobileitt632.firebasestorage.app',
  );

  /// Web configuration (placeholder)

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-i-WUjt9xy7c7x-1Eow-aCHIn862i820',
    appId: '1:992265233794:android:2a2fefed95f62dd83a5b9b',
    messagingSenderId: '992265233794',
    projectId: 'mobileitt632',
    storageBucket: 'mobileitt632.firebasestorage.app',
  );

  /// Android configuration (placeholder)

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Eolg01yraY18G7CDAcei5vSciKN3_Fk',
    appId: '1:992265233794:ios:f1a85b5bb07343c13a5b9b',
    messagingSenderId: '992265233794',
    projectId: 'mobileitt632',
    storageBucket: 'mobileitt632.firebasestorage.app',
    iosBundleId: 'com.pushup.pushupApp',
  );

  /// iOS configuration (placeholder)

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Eolg01yraY18G7CDAcei5vSciKN3_Fk',
    appId: '1:992265233794:ios:f1a85b5bb07343c13a5b9b',
    messagingSenderId: '992265233794',
    projectId: 'mobileitt632',
    storageBucket: 'mobileitt632.firebasestorage.app',
    iosBundleId: 'com.pushup.pushupApp',
  );

  /// macOS configuration (placeholder)

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsYOGLwHIQmFqplBD49WZ6nVXw7E4QdjI',
    appId: '1:992265233794:web:0288c8ed9ae47e833a5b9b',
    messagingSenderId: '992265233794',
    projectId: 'mobileitt632',
    authDomain: 'mobileitt632.firebaseapp.com',
    storageBucket: 'mobileitt632.firebasestorage.app',
  );

}